server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           # 路由的 ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由

        - id: payment_routh2          # 路由的 ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**     # 断言，路径相匹配的进行路由
            # - After=2021-09-19T17:43:21.871+08:00[Asia/Shanghai]
            # - Cookie=username,lloam # 要求请求中含有指定 cookie
            # - Header=X-Request-Id,\d+ # 请求头要有 X-Request-Id 属性并且值为整数的正则表达式
            # - Host=**.com.mao         # 请求 Host 必须以 com.mao 为后缀 curl http://localhost:9527/payment/lb -H "Host:www.com.mao"
            # - Method=GET              # 要求请求形式为 GET 请求
            - Query=username,\d+        # 要求有参数名 username，并且值还是整数才能路由 curl http://localhost:9527/payment/lb?username=123
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka